# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xilinx/PRB/PRBF2_V6_32b_ila_V2_modtomeettiming_DelayPRBFrawto2_Zhendata_newformatting/PRBF2_V6_32b/PRBF2_V6_32b.srcs/sources_1/ip/c_shift_ram_20d_32b/c_shift_ram_20d_32b.xci
# IP: The module: 'c_shift_ram_20d_32b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xilinx/PRB/PRBF2_V6_32b_ila_V2_modtomeettiming_DelayPRBFrawto2_Zhendata_newformatting/PRBF2_V6_32b/PRBF2_V6_32b.srcs/sources_1/ip/c_shift_ram_20d_32b/c_shift_ram_20d_32b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_20d_32b'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/xilinx/PRB/PRBF2_V6_32b_ila_V2_modtomeettiming_DelayPRBFrawto2_Zhendata_newformatting/PRBF2_V6_32b/PRBF2_V6_32b.srcs/sources_1/ip/c_shift_ram_20d_32b/c_shift_ram_20d_32b.xci
# IP: The module: 'c_shift_ram_20d_32b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xilinx/PRB/PRBF2_V6_32b_ila_V2_modtomeettiming_DelayPRBFrawto2_Zhendata_newformatting/PRBF2_V6_32b/PRBF2_V6_32b.srcs/sources_1/ip/c_shift_ram_20d_32b/c_shift_ram_20d_32b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_20d_32b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
